<h1>Terms and conditions:</h1>
<p>Last updated:  (<?php echo date("d-M-Y"); ?>)</p>
<p>
Please read these terms carefully before using the www.edorica.com and services provided by Edorica Inc.
As a condition of use, you promise not to use the services that is unlawful or prohibited by these terms and by agreeing those conditions
The contents, logo and other visual media on this website are protected by copyright laws so they may not be used by third parties for any purpose 
To share privacy contents on this website. Users may use the contents for their own purpose and may not share other user’s content on this website
User’s comments on this website’s article are available to everyone visiting our platforms Customer support. We have obligations to provide any kind of support on about using our platforms at anytime
Fail to reach those terms may lead to user’s account termination on this website. Also if they post unauthorized contents that may breach country’s laws
Contact us finally   
</p>

<h2>Privacy policy</h2>
<p>
This policy intends to inform you how we use and protect the personal identifiable information that is collected from our platform. For purposes of this policy, this information is termed “private information”, and is consistent with the Rwandan Constitution of 2003 as amended up to date (under art.22) which protects personal private information. No personal information shall be collected from you, unless you provide it voluntarily.
We consider the security of all personal data very seriously. We take precautions to maintain the security, confidentiality, and integrity of the information we collect at this site. Such measures include access controls designed to limit access to the information to the extent necessary to accomplish our mission. We also employ various security technologies to protect the information stored on our systems. To safeguard your personal data, all electronic storage and transmission of personal data are secured with appropriate security technologies.
Cookies are pieces of information generated by a web server and stored in the user’s computer, ready for future access. Cookies make use of user-specific information transmitted by the web server onto the user’s computer so that the information might be available for later access by itself or other servers. So we use secure cookies to make our platform very efficient for use 
We may revise this Privacy Policy from time to time and when such a change is made; we will post a revised version on this Website. Please note that changes are effective when they are posted and it is your responsibility to read the Privacy Policy from time to time in order that you are aware of any such change. In our sole discretion, and if you are a registered user, we may notify you via email associated with your account.
</p>
